"""Baseline: tables, privileges and row level security.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-09-09

Three things happen here, and the second and third are the ones that are easy
to omit and fatal to omit.

1. The tables, from the declarative metadata. A baseline migration is the one
   place where generating from metadata is preferable to hand-writing every
   column: there is no earlier state to migrate from, and a transcription slip
   would silently disagree with the models. Later migrations are ordinary
   autogenerated diffs.

2. Privileges. ``ledger_app`` gets DML and nothing else. It cannot create,
   alter or drop, so it cannot own a table, so row level security applies to
   it. Ownership is the whole game: PostgreSQL exempts a table's owner from
   RLS, and an application connecting as the owner has no isolation while
   every isolation test still passes.

3. Policies. ``FORCE ROW LEVEL SECURITY`` as well as ``ENABLE``, so that even
   if the application role ever did come to own a table the policies would
   still apply. Belt and braces, because the failure is silent.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

from app.db.base import Base
from app.db.models import SHARED_TABLES, TENANT_TABLES

revision: str = "0001_baseline"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

APP_ROLE = "ledger_app"

#: The tenant predicate.
#:
#: ``current_setting(..., true)`` returns NULL rather than raising when the
#: setting is absent, and NULLIF guards the empty string, because casting '' to
#: uuid raises. Both matter: a policy that errors on an unset tenant turns every
#: unscoped query into a 500, and a policy that raises inside a transaction is
#: harder to reason about than one that simply matches nothing.
#:
#: With no tenant set this evaluates to NULL, so no row matches. Returning
#: nothing is the correct answer for a query that forgot to establish identity.
PREDICATE = "user_id = NULLIF(current_setting('app.user_id', true), '')::uuid"

CATEGORY_PREDICATE = (
    "user_id IS NULL OR user_id = NULLIF(current_setting('app.user_id', true), '')::uuid"
)


def upgrade() -> None:
    bind = op.get_bind()

    # -- 1. Tables --------------------------------------------------------
    Base.metadata.create_all(bind=bind)

    # -- 2. Privileges ----------------------------------------------------
    op.execute(f"GRANT USAGE ON SCHEMA public TO {APP_ROLE}")
    op.execute(
        f"GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO {APP_ROLE}"
    )
    op.execute(f"GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO {APP_ROLE}")
    # Applies to tables created by later migrations, so a new table is covered
    # without anyone remembering to add a grant.
    op.execute(
        "ALTER DEFAULT PRIVILEGES IN SCHEMA public "
        f"GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO {APP_ROLE}"
    )

    # -- 3. Row level security --------------------------------------------
    for table in TENANT_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING ({PREDICATE}) WITH CHECK ({PREDICATE})"
        )

    # Categories are half shared. A system category (user_id IS NULL) is
    # readable by everyone, because the built-in taxonomy is not anybody's
    # private data. WITH CHECK omits the NULL branch deliberately: a tenant may
    # read system categories but may not create one, which would make it
    # visible to every other tenant.
    op.execute("ALTER TABLE categories ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE categories FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY tenant_isolation ON categories "
        f"USING ({CATEGORY_PREDICATE}) WITH CHECK ({PREDICATE})"
    )

    # merchants and merchant_aliases are deliberately cross-tenant and carry no
    # user_id. The alias cache warming once for everybody is what makes the
    # tenth Singapore user shopping at FairPrice cost nothing, and it is the
    # reason the LLM bill tracks distinct new merchants rather than transaction
    # volume (ADR-006).
    #
    # Nothing tenant-identifying may be written here. That is enforced upstream
    # by the transfer filter, which excludes person-to-person rows before the
    # resolver runs, and by TC-REV-011.
    for table in SHARED_TABLES:
        op.execute(f"COMMENT ON TABLE {table} IS 'Cross-tenant by design. No RLS. See ADR-006.'")

    # users and audit_log carry no policy, for different reasons.
    #
    # users: sign-in has to find an account before an account is known, so a
    # policy keyed on the current tenant would make logging in impossible. All
    # access goes through the auth repository.
    #
    # audit_log: actor_user_id has no foreign key so records survive the
    # deletion of the account they describe. It is evidence, not tenant data,
    # and is not read by any tenant-facing endpoint.
    op.execute(
        "COMMENT ON TABLE users IS "
        "'No RLS: sign-in must resolve an account before identity exists.'"
    )
    op.execute(
        "COMMENT ON TABLE audit_log IS "
        "'No RLS: evidence, survives account deletion. actor_user_id has no FK by design.'"
    )


def downgrade() -> None:
    for table in (*TENANT_TABLES, "categories"):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")
    Base.metadata.drop_all(bind=op.get_bind())
